In [63]:
import torch
import numpy as np

In [64]:
array=[[1,2,3],[1,2,3]] #liste oluşturuyoruz

In [65]:
numpy_array=np.array(array) #listemizi numpy arrayine dönüştürüyoruz

In [66]:
torch_tensor=torch.Tensor(array) #listemizi pytorch tensorüne çeviriyoruz
type(torch_tensor)

torch.Tensor

In [67]:
print(torch_tensor)
print("boyut:",torch_tensor.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
boyut: torch.Size([2, 3])


In [68]:
torch_tensor=torch.from_numpy(numpy_array) #numpy arrayini pytorch tensorüne cevirme
print(torch_tensor)
print("boyut:",torch_tensor.size())

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)
boyut: torch.Size([2, 3])


In [69]:
torch.ones((5,5)) #np gibi 1 lerden oluşan matris oluşturma
torch.zeros((5,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [70]:
torch.rand(5,5)# 5 e 5 0-1 arasından sayılardan oluşan tensor


tensor([[0.1319, 0.1374, 0.4639, 0.6044, 0.9310],
        [0.1320, 0.0483, 0.0272, 0.4825, 0.2089],
        [0.0801, 0.5695, 0.2792, 0.6079, 0.0613],
        [0.3502, 0.3700, 0.6009, 0.9051, 0.7174],
        [0.6498, 0.9624, 0.4966, 0.0352, 0.5223]])

In [71]:
float_tensor=torch.FloatTensor(5,3)
print(float_tensor)

tensor([[0.1319, 0.1374, 0.4639, 0.6044, 0.9310],
        [0.1320, 0.0483, 0.0272, 0.4825, 0.2089],
        [0.0801, 0.5695, 0.2792, 0.6079, 0.0613],
        [0.3502, 0.3700, 0.6009, 0.9051, 0.7174],
        [0.6498, 0.9624, 0.4966, 0.0352, 0.5223]])
